### ISSUE TITLE
Exception: not find lib assign_box_cuda

### ISSUE THREAD

**Issue by Mahmood-Hussain** [xytpai/fcos#21]

**Comment by Mahmood-Hussain** [comment]
What are the requirements to run this because I am getting this error


`
 python setup.py install
running install
running bdist_egg
running egg_info
writing nms_cuda.egg-info/PKG-INFO
writing dependency_links to nms_cuda.egg-info/dependency_links.txt
writing top-level names to nms_cuda.egg-info/top_level.txt
reading manifest file 'nms_cuda.egg-info/SOURCES.txt'
writing manifest file 'nms_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'nms_cuda' extension
creating /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6
Emitting ninja build file /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda-11.2/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_kernel.o.d -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/TH -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-11.2/include -I/home/mahmood/anaconda3/envs/cu10/include/python3.6m -c -c /home/mahmood/fcos/libs/nms_cuda/nms_kernel.cu -o /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/mahmood/fcos/libs/nms_cuda/nms_kernel.cu: In function ‘at::Tensor nms_cuda(at::Tensor, float)’:
/home/mahmood/fcos/libs/nms_cuda/nms_kernel.cu:72:62: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   AT_ASSERTM(boxes.type().is_cuda(), "boxes must be a CUDA tensor");
                                                              ^
/home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:1: note: declared here
   DeprecatedTypeProperties & type() const {
 ^ ~~
/home/mahmood/fcos/libs/nms_cuda/nms_kernel.cu:81:50: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   scalar_t* boxes_dev = boxes_sorted.data<scalar_t>();
                                                  ^
/home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:398:1: note: declared here
   T * data() const {
 ^ ~~
/home/mahmood/fcos/libs/nms_cuda/nms_kernel.cu:109:46: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   int64_t* keep_out = keep.data<int64_t>();
                                              ^
/home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:398:1: note: declared here
   T * data() const {
 ^ ~~
[2/2] c++ -MMD -MF /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_cuda.o.d -pthread -B /home/mahmood/anaconda3/envs/cu10/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/TH -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-11.2/include -I/home/mahmood/anaconda3/envs/cu10/include/python3.6m -c -c /home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp -o /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_cuda.o 
c++ -MMD -MF /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_cuda.o.d -pthread -B /home/mahmood/anaconda3/envs/cu10/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/TH -I/home/mahmood/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-11.2/include -I/home/mahmood/anaconda3/envs/cu10/include/python3.6m -c -c /home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp -o /home/mahmood/fcos/libs/nms_cuda/build/temp.linux-x86_64-3.6/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/Parallel.h:140:0,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:2:
/home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/ParallelOpenMP.h:83:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
In file included from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/mahmood/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:2:
/home/mahmood/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/home/mahmood/fcos/libs/nms_cuda/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/mahmood/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    'build_ext': BuildExtension
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/mahmood/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/mahmood/anaconda3/envs/cu10/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/mahmood/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/mahmood/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/mahmood/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension


`
